name: SSOT Draft Builder (22:05 KST)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 13 * * *"  # 22:05 KST (UTC 기준)

permissions:
  contents: write

concurrency:
  group: ssot-draft-2205
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (data repo)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install requests python-dateutil

      - name: Build DRAFT_1ST from SSOT (fail-fast rules)
        env:
          SSOT_MANIFEST_URL: "https://raw.githubusercontent.com/KRTeknic/nba-collector-data/main/latest/manifest.json"
          SSOT_ODDS_URL: "https://raw.githubusercontent.com/KRTeknic/nba-collector-data/main/latest/espn_odds.json"
          # optional: 같은 latest 폴더에 있으면 사용 가능
          SSOT_SCOREBOARD_URL: "https://raw.githubusercontent.com/KRTeknic/nba-collector-data/main/latest/espn_scoreboard.json"
          SSOT_INJURY_PDF_URL: "https://raw.githubusercontent.com/KRTeknic/nba-collector-data/main/latest/nba_injury_report.pdf"
        run: |
          python - << 'PY'
          import os, json
          from pathlib import Path
          from datetime import datetime, timezone
          from zoneinfo import ZoneInfo
          import requests

          KST = ZoneInfo("Asia/Seoul")
          ET  = ZoneInfo("America/New_York")

          now_utc = datetime.now(timezone.utc)
          now_kst = now_utc.astimezone(KST)
          now_et  = now_utc.astimezone(ET)

          date_et = now_et.strftime("%Y%m%d")
          slot = "2205"  # 이 워크플로우는 22:05 KST 전용

          latest_dir = Path("analysis/latest")
          logs_dir   = Path("analysis/logs")
          cfg_dir    = Path("analysis/config")
          latest_dir.mkdir(parents=True, exist_ok=True)
          logs_dir.mkdir(parents=True, exist_ok=True)
          cfg_dir.mkdir(parents=True, exist_ok=True)

          sentinel = logs_dir / f"{date_et}_{slot}.captured"
          if sentinel.exists():
            # 중복 실행 방지: 오늘 이미 캡처되면 스킵 파일만 유지
            md = (
              "[SNAPSHOT_SOURCE]\n"
              f"- verified_at (ET/KST): {now_et.isoformat()} / {now_kst.isoformat()}\n"
              "- status: SKIPPED_ALREADY_CAPTURED\n"
            )
            (latest_dir / "draft_1st.md").write_text(md, encoding="utf-8")
            (latest_dir / "draft_1st.json").write_text(json.dumps({
              "status":"SKIPPED_ALREADY_CAPTURED",
              "verified_at_et": now_et.isoformat(),
              "verified_at_kst": now_kst.isoformat(),
              "date_et": date_et,
              "slot": slot
            }, ensure_ascii=False, indent=2), encoding="utf-8")
            raise SystemExit(0)

          manifest_url = os.getenv("SSOT_MANIFEST_URL")
          odds_url     = os.getenv("SSOT_ODDS_URL")
          sb_url       = os.getenv("SSOT_SCOREBOARD_URL")
          injury_pdf   = os.getenv("SSOT_INJURY_PDF_URL")

          def fetch_json(url, timeout=30):
            r = requests.get(url, timeout=timeout)
            r.raise_for_status()
            return r.json()

          manifest = None
          odds = None
          sb_ok = None

          manifest_status = {}
          errors = []

          # 1) manifest
          try:
            manifest = fetch_json(manifest_url)
            manifest_status = (manifest.get("status") or {})
          except Exception as e:
            errors.append(f"manifest_fetch_failed: {e}")

          # 2) fail-fast: ESPN_ODDS
          espn_odds_status = (manifest_status.get("ESPN_ODDS") if manifest_status else None)
          market_available = bool(espn_odds_status and str(espn_odds_status).startswith("OK"))

          # 3) odds json (if market ok)
          if market_available:
            try:
              odds = fetch_json(odds_url)
            except Exception as e:
              market_available = False
              errors.append(f"espn_odds_fetch_failed: {e}")

          # 4) scoreboard availability flag (optional)
          try:
            if sb_url:
              _ = requests.get(sb_url, timeout=15)
              sb_ok = (_.status_code == 200)
          except Exception:
            sb_ok = False

          # 5) open anchor (optional local file)
          # analysis/config/open_anchor.json (사용자 OPEN 앵커를 파일로 보관할 때 사용)
          anchor_path = cfg_dir / "open_anchor.json"
          open_anchor = None
          if anchor_path.exists():
            try:
              open_anchor = json.loads(anchor_path.read_text(encoding="utf-8"))
            except Exception:
              open_anchor = None

          # Helper: drift calc (단순 매칭: away/home key)
          def parse_details(details: str):
            # e.g. "ORL -7.5" / "CHI +4.5"
            if not details or not isinstance(details, str): return None, None
            parts = details.strip().split()
            if len(parts) < 2: return None, None
            team = parts[0].strip().upper()
            try:
              val = float(parts[1])
            except Exception:
              return team, None
            return team, val

          market_rows_md = []
          drift_md = []
          rows = []

          if market_available and odds:
            for r in (odds.get("rows") or []):
              away = r.get("away"); home = r.get("home")
              details = r.get("details"); total = r.get("total")
              provider = r.get("provider"); start_utc = r.get("start_utc")
              team, spread = parse_details(details)

              rows.append(r)

              market_rows_md.append(
                f"- {away}@{home} | spread(details): {details} | total: {total} | provider: {provider} | start_utc: {start_utc}"
              )

              # drift vs OPEN anchor (if present)
              if open_anchor and isinstance(open_anchor, dict):
                key = f"{away}@{home}"
                a = open_anchor.get(key)
                if isinstance(a, dict):
                  # anchor spread is stored as "details" style or numeric; we handle numeric only here
                  a_spread = a.get("spread")  # numeric from perspective of details team
                  a_total  = a.get("total")
                  d_spread = None
                  d_total = None
                  if (a_spread is not None) and (spread is not None):
                    try: d_spread = float(spread) - float(a_spread)
                    except: d_spread = None
                  if (a_total is not None) and (total is not None):
                    try: d_total = float(total) - float(a_total)
                    except: d_total = None
                  drift_md.append(
                    f"- {key} | Spread Δ: {d_spread if d_spread is not None else 'n/a'} | Total Δ: {d_total if d_total is not None else 'n/a'}"
                  )

          # INJURY snapshot: manifest link if present; pdf URL 자체는 “있으면 확인” 용
          injury_status = (manifest_status.get("NBA_INJURY_PDF") if manifest_status else None)
          if not injury_status:
            injury_status = "UNAVAILABLE (manifest missing)"

          # UNRESOLVED / FAIL-FAST flags
          unresolved = []
          if not market_available:
            unresolved.append("MARKET=UNAVAILABLE (FAIL-FAST: ESPN_ODDS not OK)")
          if manifest_status and not str(manifest_status.get("ESPN_SCOREBOARD","")).startswith("OK"):
            unresolved.append("SCOREBOARD=UNAVAILABLE")
          if manifest_status and not str(manifest_status.get("NBA_INJURY_PDF","")).startswith("OK"):
            unresolved.append("INJURY=FAILED (allow AUX check, conflicts -> UNRESOLVED)")

          # DRAFT: 오늘은 “시장/부상 상태 기반 초안 후보”만 (PLAY/PASS)
          # 실제 픽엔진은 별도 모듈에서 확장 예정. 여기서는 규칙만 강제.
          draft = {
            "status": "OK" if market_available else "MARKET_UNAVAILABLE",
            "verified_at_et": now_et.isoformat(),
            "verified_at_kst": now_kst.isoformat(),
            "source_urls": {
              "manifest": manifest_url,
              "odds": odds_url,
              "scoreboard": sb_url,
              "injury_pdf": injury_pdf
            },
            "manifest_status": manifest_status,
            "unresolved": unresolved,
            "candidates": [],
          }

          # 최소 동작: market unavailable이면 후보 없이 종료(하지만 파일은 남김)
          if market_available:
            draft["candidates"] = [{"label":"PASS (engine not yet integrated)", "reason":"DRAFT pipeline OK; pick engine integration next"}]

          # Markdown output (요구 블록 순서 고정)
          md_lines = []
          md_lines.append("[SNAPSHOT_SOURCE]")
          md_lines.append(f"- verified_at (ET/KST): {now_et.isoformat()} / {now_kst.isoformat()}")
          md_lines.append(f"- source_urls: {manifest_url} , {odds_url}")
          md_lines.append(f"- manifest.status: {json.dumps(manifest_status, ensure_ascii=False)}")
          md_lines.append("")

          md_lines.append("[MARKET_SNAPSHOT_LOG]")
          if market_available:
            md_lines.extend(market_rows_md or ["- (rows empty)"])
          else:
            md_lines.append("- MARKET=UNAVAILABLE (FAIL-FAST)")
          if drift_md:
            md_lines.append("")
            md_lines.append("- OPEN 대비 드리프트(변동값)")
            md_lines.extend(drift_md)
          md_lines.append("")

          md_lines.append("[INJURY_SNAPSHOT_LOG]")
          md_lines.append(f"- nba_injury_report.pdf: {injury_status}")
          md_lines.append("- AUX(가능): RotoWire lineups / CBS injuries / ESPN injury page (충돌 시 UNRESOLVED)")
          md_lines.append("")

          md_lines.append("[UNRESOLVED_ZONE]")
          if unresolved:
            for u in unresolved:
              md_lines.append(f"- {u}")
          else:
            md_lines.append("- (none)")
          md_lines.append("")

          md_lines.append("[DRAFT_ANALYSIS_1ST]")
          md_lines.append("- 픽조합 v1.0 준수(같은 경기 핸디+언오버 한 조합 중복 금지, 최소 2폴)")
          if draft["candidates"]:
            for c in draft["candidates"]:
              md_lines.append(f"- {c['label']}: {c['reason']}")
          else:
            md_lines.append("- 후보 없음 (MARKET UNAVAILABLE 또는 엔진 미연결)")
          md_lines.append("")

          md_lines.append("[PROCESS_LOG]")
          md_lines.append(f"- opened: manifest, odds (scoreboard/pdf optional)")
          if errors:
            md_lines.append(f"- errors: {errors}")
          else:
            md_lines.append("- errors: none")
          md_lines.append("")

          (latest_dir / "draft_1st.md").write_text("\n".join(md_lines), encoding="utf-8")
          (latest_dir / "draft_1st.json").write_text(json.dumps(draft, ensure_ascii=False, indent=2), encoding="utf-8")

          sentinel.write_text(f"captured_at_utc={now_utc.isoformat()}\n", encoding="utf-8")
          print("OK: wrote analysis/latest/draft_1st.md, draft_1st.json, sentinel:", sentinel.as_posix())
          PY

      - name: Commit & push outputs
        run: |
          git config user.name "nba-bot"
          git config user.email "nba-bot@users.noreply.github.com"
          git add analysis
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "SSOT draft_1st $(date -u +'%Y%m%dT%H%M%SZ')"
          git push
